baseURL = 'https://baeseokjae.github.io/blog/'
languageCode = 'en-us'
title = 'My Blog'
theme = 'PaperMod'
[pagination]
  pagerSize = 10

[params]
  env = 'production'
  description = 'AI-powered blog'
  author = 'baeseokjae'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = true

[params.homeInfoParams]
  Title = 'Welcome'
  Content = 'Latest articles'

[outputs]
  home = ['HTML', 'RSS', 'JSON']
